#!/bin/bash

# Interactive Supabase Credential Setup Script
# This will help you set up your .env file with actual Supabase credentials

echo "=========================================="
echo "  Supabase Credential Setup Wizard"
echo "=========================================="
echo ""
echo "This script will help you configure your Supabase credentials."
echo ""
echo "📋 STEPS TO GET YOUR CREDENTIALS:"
echo ""
echo "1. Open your browser and go to: https://app.supabase.com"
echo "2. Select your project (or create one if you don't have it)"
echo "3. Click the ⚙️  'Project Settings' icon (bottom left)"
echo "4. Go to 'API' section"
echo "5. You'll see:"
echo "   - Project URL"
echo "   - Project API keys (anon/public and service_role)"
echo ""
echo "6. Scroll down to 'JWT Settings' section"
echo "   - You'll find the JWT Secret there"
echo ""
echo "=========================================="
echo ""

# Read the current .env file location
ENV_FILE="/home/user/YDA4/.env"

echo "I will now ask you for each credential."
echo "Copy/paste them from Supabase dashboard."
echo ""
echo "Press Ctrl+C at any time to cancel."
echo ""

# Read Project URL
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  SUPABASE PROJECT URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "From Supabase Dashboard > Project Settings > API"
echo "Look for: 'Project URL'"
echo "Example: https://abcdefghijklmn.supabase.co"
echo ""
read -p "Enter your SUPABASE_URL: " SUPABASE_URL

# Read Anon Key
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  SUPABASE ANON KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "From Supabase Dashboard > Project Settings > API"
echo "Look for: 'Project API keys' > 'anon' 'public'"
echo "Click 'Copy' button next to it"
echo ""
read -p "Enter your SUPABASE_ANON_KEY: " SUPABASE_ANON_KEY

# Read Service Role Key
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  SUPABASE SERVICE ROLE KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "From Supabase Dashboard > Project Settings > API"
echo "Look for: 'Project API keys' > 'service_role' 'secret'"
echo "Click 'Reveal' then 'Copy'"
echo "⚠️  WARNING: Keep this secret! Don't share it!"
echo ""
read -p "Enter your SUPABASE_SERVICE_KEY: " SUPABASE_SERVICE_KEY

# Read JWT Secret
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  SUPABASE JWT SECRET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "From Supabase Dashboard > Project Settings > API"
echo "Scroll down to 'JWT Settings' section"
echo "Look for: 'JWT Secret'"
echo "⚠️  This is NOT the same as the service key above!"
echo ""
read -p "Enter your SUPABASE_JWT_SECRET: " SUPABASE_JWT_SECRET

# Validate inputs
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 VALIDATING YOUR INPUTS..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

VALID=true

if [[ ! "$SUPABASE_URL" =~ ^https://.*\.supabase\.co$ ]]; then
    echo "❌ SUPABASE_URL doesn't look right. Should be: https://xxxxx.supabase.co"
    VALID=false
else
    echo "✅ SUPABASE_URL looks good"
fi

if [[ ! "$SUPABASE_ANON_KEY" =~ ^eyJ ]]; then
    echo "❌ SUPABASE_ANON_KEY doesn't look right. Should start with 'eyJ'"
    VALID=false
else
    echo "✅ SUPABASE_ANON_KEY looks good"
fi

if [[ ! "$SUPABASE_SERVICE_KEY" =~ ^eyJ ]]; then
    echo "❌ SUPABASE_SERVICE_KEY doesn't look right. Should start with 'eyJ'"
    VALID=false
else
    echo "✅ SUPABASE_SERVICE_KEY looks good"
fi

if [[ -z "$SUPABASE_JWT_SECRET" ]]; then
    echo "❌ SUPABASE_JWT_SECRET is empty"
    VALID=false
else
    echo "✅ SUPABASE_JWT_SECRET looks good"
fi

if [ "$VALID" = false ]; then
    echo ""
    echo "❌ Some credentials don't look right. Please double-check them."
    echo "Run this script again: bash setup_supabase_env.sh"
    exit 1
fi

# Write to .env file
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 SAVING TO .env FILE..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cat > "$ENV_FILE" <<EOF
# Supabase Configuration
# Generated by setup wizard

# Supabase Project URL
SUPABASE_URL=$SUPABASE_URL

# Supabase Anon/Public Key (safe to use in frontend)
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Supabase JWT Secret (required for backend to verify user tokens)
SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET

# Supabase Service Role Key (DO NOT expose in frontend - backend only)
SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY

# Frontend Build Variables (for Vite)
VITE_SUPABASE_URL=\${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=\${SUPABASE_ANON_KEY}

# Environment
ENVIRONMENT=development
EOF

echo "✅ Saved credentials to: $ENV_FILE"
echo ""

# Test connection
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 TESTING CONNECTION..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if command -v python3 &> /dev/null; then
    echo "Running connection test..."
    python3 /home/user/YDA4/test_supabase_connection.py
else
    echo "⚠️  Python3 not found, skipping connection test"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SETUP COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Run the Supabase migration (create 'sources' table):"
echo "   - Go to: https://app.supabase.com"
echo "   - SQL Editor > New Query"
echo "   - Copy contents of: app/backend/migrations/001_create_sources_table.sql"
echo "   - Paste and click 'Run'"
echo ""
echo "2. Restart your Docker containers:"
echo "   cd /home/user/YDA4"
echo "   docker compose down"
echo "   docker compose up -d"
echo ""
echo "3. Test processing a podcast!"
echo ""
